// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "MainUI.h"

Fl_Double_Window* MainUI::make_window() {
  { window = new Fl_Double_Window(800, 600, "NodeEditor");
    window->user_data((void*)(this));
    { workspace = new Workspace(0, 0, 600, 600);
      workspace->box(FL_THIN_DOWN_BOX);
      workspace->color(FL_BACKGROUND_COLOR);
      workspace->selection_color(FL_BACKGROUND_COLOR);
      workspace->labeltype(FL_NORMAL_LABEL);
      workspace->labelfont(0);
      workspace->labelsize(14);
      workspace->labelcolor(FL_FOREGROUND_COLOR);
      workspace->align(Fl_Align(FL_ALIGN_CENTER));
      workspace->when(FL_WHEN_RELEASE);
    } // Workspace* workspace
    window->end();
  } // Fl_Double_Window* window
  return window;
}
