// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef MainUI_h
#define MainUI_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include "Workspace.h"

class MainUI {
public:
  Fl_Double_Window* make_window();
  Fl_Double_Window *window;
  Workspace *workspace;
};
#endif
