// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "MainUI.h"

Fl_Menu_Item MainUI::menu_[] = {
 {"&File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Open...", 0x40006f,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Save", 0x400073,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save &as...", 0x410073,  0, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"E&xit", 0x400071,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Edit", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Select &all", 0x400061,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Select &none", 0x410061,  0, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"C&ut", 0x400078,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Copy", 0x400063,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Paste", 0x400076,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Duplicate", 0x400064,  0, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Group", 0x400067,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Group", 0x410067,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* MainUI::mnu_file_open = MainUI::menu_ + 1;
Fl_Menu_Item* MainUI::mnu_file_save = MainUI::menu_ + 2;
Fl_Menu_Item* MainUI::mnu_file_saveas = MainUI::menu_ + 3;
Fl_Menu_Item* MainUI::mnu_file_exit = MainUI::menu_ + 4;
Fl_Menu_Item* MainUI::mnu_edit_select_all = MainUI::menu_ + 7;
Fl_Menu_Item* MainUI::mnu_edit_select_none = MainUI::menu_ + 8;
Fl_Menu_Item* MainUI::mnu_edit_cut = MainUI::menu_ + 9;
Fl_Menu_Item* MainUI::mnu_edit_copy = MainUI::menu_ + 10;
Fl_Menu_Item* MainUI::mnu_edit_paste = MainUI::menu_ + 11;
Fl_Menu_Item* MainUI::mnu_edit_dup = MainUI::menu_ + 12;
Fl_Menu_Item* MainUI::mnu_edit_group = MainUI::menu_ + 13;
Fl_Menu_Item* MainUI::mnu_edit_ungroup = MainUI::menu_ + 14;

Fl_Double_Window* MainUI::make_window() {
  { window = new Fl_Double_Window(800, 600, "NodeEditor");
    window->user_data((void*)(this));
    { workspace = new Workspace(0, 20, 565, 565);
      workspace->box(FL_THIN_DOWN_BOX);
      workspace->color(FL_BACKGROUND_COLOR);
      workspace->selection_color(FL_BACKGROUND_COLOR);
      workspace->labeltype(FL_NORMAL_LABEL);
      workspace->labelfont(0);
      workspace->labelsize(14);
      workspace->labelcolor(FL_FOREGROUND_COLOR);
      workspace->align(Fl_Align(FL_ALIGN_CENTER));
      workspace->when(FL_WHEN_RELEASE);
      Fl_Group::current()->resizable(workspace);
    } // Workspace* workspace
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 800, 20);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { scroll_h = new Fl_Scrollbar(0, 585, 600, 15);
      scroll_h->type(1);
    } // Fl_Scrollbar* scroll_h
    { scroll_v = new Fl_Scrollbar(565, 20, 15, 565);
    } // Fl_Scrollbar* scroll_v
    { Fl_Group* o = new Fl_Group(580, 19, 220, 581);
      { tb_up = new Fl_Button(580, 20, 25, 25, "@8>");
      } // Fl_Button* tb_up
      { tb_down = new Fl_Button(605, 20, 25, 25, "@2>");
      } // Fl_Button* tb_down
      { Fl_Tile* o = new Fl_Tile(580, 45, 220, 555);
        o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
        { node_tree = new Fl_Tree(580, 45, 220, 275);
        } // Fl_Tree* node_tree
        { properties = new Fl_Scroll(580, 320, 220, 280);
          properties->box(FL_DOWN_BOX);
          properties->color(FL_BACKGROUND2_COLOR);
          properties->end();
        } // Fl_Scroll* properties
        o->end();
        Fl_Group::current()->resizable(o);
      } // Fl_Tile* o
      { tb_export = new Fl_Button(630, 20, 25, 25, "@+");
      } // Fl_Button* tb_export
      o->end();
    } // Fl_Group* o
    window->end();
  } // Fl_Double_Window* window
  return window;
}
